export const ICON_EMOJI: Record<string, string> = {
  chicken: "🍗",
  beef: "🥩",
  pork: "🥓",
  bacon: "🥓",
  ham: "🍖",
  sausage: "🌭",
  turkey: "🦃",
  lamb: "🐑",
  fish: "🐟",
  shrimp: "🦐",
  eggs: "🥚",
  tofu: "🫙",
  tempeh: "🟫",
  lentils: "🫘",
  chickpeas: "🫘",
  beans: "🫘",
  edamame: "🫛",
  onion: "🧅",
  garlic: "🧄",
  tomato: "🍅",
  potato: "🥔",
  "sweet-potato": "🍠",
  carrot: "🥕",
  broccoli: "🥦",
  cauliflower: "🥦",
  spinach: "🥬",
  kale: "🥬",
  lettuce: "🥬",
  cucumber: "🥒",
  zucchini: "🥒",
  pepper: "🫑",
  mushroom: "🍄",
  celery: "🌿",
  corn: "🌽",
  peas: "🫛",
  "green-beans": "🫘",
  asparagus: "🌿",
  cabbage: "🥬",
  eggplant: "🍆",
  leek: "🧅",
  "bok-choy": "🥬",
  "brussels-sprouts": "🥦",
  artichoke: "🌿",
  apple: "🍎",
  banana: "🍌",
  lemon: "🍋",
  lime: "🍋",
  orange: "🍊",
  avocado: "🥑",
  strawberry: "🍓",
  blueberry: "🫐",
  mango: "🥭",
  pineapple: "🍍",
  grapes: "🍇",
  peach: "🍑",
  pear: "🍐",
  raspberry: "🍓",
  milk: "🥛",
  butter: "🧈",
  cheese: "🧀",
  cream: "🥛",
  "cream-cheese": "🧀",
  yogurt: "🥛",
  rice: "🍚",
  pasta: "🍝",
  bread: "🍞",
  flour: "🌾",
  quinoa: "🌾",
  oats: "🌾",
  couscous: "🌾",
  tortilla: "🫓",
  noodles: "🍜",
  breadcrumbs: "🍞",
  oil: "🫙",
  "soy-sauce": "🫙",
  "fish-sauce": "🫙",
  sauce: "🫙",
  vinegar: "🫙",
  "tomato-paste": "🍅",
  tomatoes: "🍅",
  "coconut-milk": "🥥",
  broth: "🍲",
  honey: "🍯",
  "maple-syrup": "🍁",
  sugar: "🍬",
  mustard: "🟡",
  ketchup: "🔴",
  "hot-sauce": "🌶️",
  "peanut-butter": "🥜",
  tahini: "🫙",
  salt: "🧂",
  "pepper-spice": "⚫",
  cumin: "🟤",
  paprika: "🔴",
  oregano: "🌿",
  basil: "🌿",
  ginger: "🫚",
  turmeric: "🟡",
  chili: "🌶️",
  "garlic-spice": "🧄",
  "onion-spice": "🧅",
  cinnamon: "🟤",
  thyme: "🌿",
  rosemary: "🌿",
  "bay-leaves": "🍃",
  curry: "🟡",
  nuts: "🥜",
  seeds: "🌱",
};

export const CATEGORY_LABEL: Record<string, string> = {
  protein: "Proteins",
  vegetable: "Vegetables",
  fruit: "Fruits",
  dairy: "Dairy",
  grain: "Grains & Starches",
  pantry: "Pantry & Sauces",
  spice: "Spices & Herbs",
  nut: "Nuts & Seeds",
};

export const CATEGORY_ORDER = [
  "protein",
  "vegetable",
  "fruit",
  "dairy",
  "grain",
  "pantry",
  "spice",
  "nut",
];

export function getEmoji(iconKey: string): string {
  return ICON_EMOJI[iconKey] ?? "🥄";
}
